<?php
if(!defined('ABSPATH')||!is_user_logged_in())exit;
$metric_rows=mis360_account_metrics();$metrics=array();$totals=array('view'=>0,'phone'=>0,'whatsapp'=>0,'directions'=>0);
foreach($metric_rows as $row){$metrics[(int)$row['firm_id']][$row['event']]=(int)$row['hits'];if(isset($totals[$row['event']]))$totals[$row['event']]+=(int)$row['hits'];}
$owned=get_posts(array('post_type'=>'firma','author'=>get_current_user_id(),'post_status'=>array('publish','pending','draft','private','future'),'numberposts'=>-1,'fields'=>'ids'));
$status_labels=array('publish'=>'Yayında','pending'=>'Onay bekliyor','draft'=>'Taslak','private'=>'Özel','future'=>'Yayın planlandı');$live=0;$pending=0;foreach($owned as $id){$status=get_post_status($id);if($status==='publish')$live++;if($status==='pending')$pending++;}
$reviews=$owned?get_comments(array('post__in'=>$owned,'status'=>'approve','type'=>'comment','number'=>10,'orderby'=>'comment_date_gmt','order'=>'DESC')):array();
$review_count=$owned?(int)get_comments(array('post__in'=>$owned,'status'=>'approve','type'=>'comment','count'=>true)):0;
?>
<?php $account_section = mis360_account_section();
$account_sections = array('destek'=>array('Destek & Mesajlar','Yöneticiye doğrudan mesaj gönderin ve yanıtları buradan takip edin.'),'ozet'=>array('Genel bakış','Hesabınızın kısa özeti ve son 30 günlük hareketler.'),'firmalar'=>array('Firmalarım','Firma başvurularınızı ve yayın durumlarını takip edin.'),'yorumlar'=>array('Yorumlar','Firmalarınıza gelen müşteri değerlendirmeleri.'),'odemeler'=>array('Paket ve ödemeler','Paket tercihleriniz ve kayıtlı ödeme durumları.'),'profil'=>array('Hesap bilgilerim','Üyelik bilgileriniz ve hesap güvenliği.'),'belgeler'=>array('Belgelerim','Firma başvurusu için gerekli belgelerinizi yönetin.'));
$account_sections['bildirimler']=array('Bildirimler','Hesabınızdaki tüm yeni gelişmeler.');$account_sections['sahiplenme']=array('Firma sahiplenme','Mevcut işletme kaydınızı hesabınıza bağlayın.');
$support_item=$account_sections['destek'];unset($account_sections['destek']);$account_sections['destek']=$support_item;
?>
<div class="mis360-account-workspace">
<aside class="mis360-account-sidebar"><span class="mis360-account-menu-label">YÖNETİM MENÜSÜ</span>
<nav class="mis360-account-nav" aria-label="Hesap menüsü"><?php $nav_index=0; foreach($account_sections as $slug=>$item): $nav_index++; ?><a href="<?php echo esc_url(mis360_account_url($slug)); ?>" <?php if($account_section===$slug)echo 'aria-current="page"'; ?>><span aria-hidden="true"><?php echo array('ozet'=>'◴','firmalar'=>'▤','yorumlar'=>'♡','odemeler'=>'▣','profil'=>'♙','belgeler'=>'▧','destek'=>'✉','bildirimler'=>'♧','sahiplenme'=>'⌂')[$slug]; ?></span><?php echo esc_html($item[0]); ?><?php if($slug==='bildirimler'&&($notice_count=mis360_notice_unread())): ?><b class="mis360-hub-badge"><?php echo (int)$notice_count; ?></b><?php endif; ?><?php if($slug==='destek' && ($unread=mis360_support_unread())): ?><b class="mis360-support-count" style="font-size:10px;background:#ff8a00;color:#13243a;padding:2px 6px;border-radius:12px"><?php echo (int)$unread; ?></b><?php endif; ?></a><?php endforeach; ?></nav>
<a class="mis360-account-sidebar-add" href="<?php echo esc_url(home_url('/firma-ekle/')); ?>">+ Firma ekle</a>
<div class="mis360-account-support"><strong>Bir sorunuz mu var?</strong><p>Başvuru ve üyelik işlemleri için bizimle iletişime geçin.</p><a href="<?php echo esc_url(mis360_account_url('destek')); ?>">Destek al →</a></div></aside>
<div class="mis360-account-content"><?php mis360_hub_flash(); ?>
<?php if(!empty($GLOBALS['mis360_firm_error'])): ?><div class="mis360-member-alert" role="alert"><?php echo esc_html($GLOBALS['mis360_firm_error']); ?></div><?php endif; ?>
<?php if(isset($_GET['firm_saved'])): ?><div class="mis360-account-notice" role="status"><?php echo $_GET['firm_saved']==='withdrawn'?'İlan yayından kaldırıldı. Bilgileri hesabınızda saklanıyor.':'Değişiklikler kaydedildi. Firma yeniden onay bekliyor.'; ?></div><?php endif; ?>
<?php if($account_section==='ozet'):
 $corrections=0;foreach($owned as $owned_id)if(get_post_status($owned_id)==='draft'&&get_post_meta($owned_id,'_mis360_review_state',true)==='changes')$corrections++;
 $tax_review=mis360_tax_review(get_current_user_id());
 if($corrections): ?><div class="mis360-account-notice"><?php echo (int)$corrections; ?> firma başvurunuz için düzeltme istendi. <a href="<?php echo esc_url(mis360_account_url('firmalar')); ?>">Gerekçeleri incele →</a></div><?php endif;
 if($tax_review['state']==='changes'): ?><div class="mis360-account-notice">Vergi levhanız için düzeltme gerekiyor. <a href="<?php echo esc_url(mis360_account_url('belgeler')); ?>">Belge incelemesini aç →</a></div><?php endif; endif; ?>
<?php if($account_section==='firmalar'&&isset($_GET['firm_edit'])){mis360_firm_editor(is_scalar($_GET['firm_edit'])?absint($_GET['firm_edit']):0);return;} ?>
<?php if($account_section!=='firmalar'): ?><div class="mis360-account-page-title"><span>HESABIM / <?php echo esc_html($account_sections[$account_section][0]); ?></span><h2><?php echo esc_html($account_sections[$account_section][0]); ?></h2><p><?php echo esc_html($account_sections[$account_section][1]); ?></p></div>
<?php endif; if($account_section==='ozet'): ?><?php if(($intent=(int)get_user_meta(get_current_user_id(),'mis360_claim_intent',true))&&mis360_claim_eligible($intent)): ?><div class="mis360-account-notice"><a href="<?php echo esc_url(add_query_arg('claim_firm',$intent,mis360_account_url('sahiplenme'))); ?>">Firma sahiplenme başvurunuza devam edin →</a></div><?php endif; ?>
<section id="account-overview" class="mis360-quiet-stats" aria-label="Hesap özeti">
<div><span>Firmalarım</span><strong><?php echo number_format_i18n(count($owned)); ?></strong><small><?php echo (int)$live; ?> yayında</small></div>
<div><span>Görüntülenme</span><strong><?php echo number_format_i18n($totals['view']); ?></strong><small>Son 30 gün</small></div>
<div><span>İletişim tıklamaları</span><strong><?php echo number_format_i18n($totals['phone']+$totals['whatsapp']); ?></strong><small>Telefon ve WhatsApp · 30 gün</small></div>
<div><span>Onay bekleyen</span><strong><?php echo number_format_i18n($pending); ?></strong><small>Firma başvurusu</small></div>
</section>
<div class="mis360-recent-firms"><header><h3>Son eklediğiniz firmalar</h3><a href="<?php echo esc_url(mis360_account_url('firmalar')); ?>">Tümünü gör →</a></header>
<?php if($firms->posts): foreach(array_slice($firms->posts,0,3) as $recent): $thumb=get_the_post_thumbnail_url($recent->ID,'thumbnail') ?: get_post_meta($recent->ID,'_firma_image_url',true); ?>
<div class="mis360-recent-row"><div class="mis360-recent-image"><?php if($thumb): ?><img src="<?php echo esc_url($thumb); ?>" alt="" width="44" height="44"><?php else: ?><span><?php echo esc_html(mb_substr($recent->post_title,0,1)); ?></span><?php endif; ?></div><div class="mis360-recent-name"><strong><?php echo esc_html($recent->post_title); ?></strong><small><?php echo esc_html(get_post_meta($recent->ID,'_firma_city',true)); ?></small></div><span class="mis360-recent-status"><?php echo esc_html(mis360_firm_review_label($recent->ID)); ?></span><?php if($recent->post_status==='publish'): ?><a href="<?php echo esc_url(get_permalink($recent)); ?>">İncele ↗</a><?php endif; ?></div>
<?php endforeach;else: ?><div class="mis360-account-welcome"><span class="mis360-welcome-icon" aria-hidden="true"><?php echo mis360_tow_symbol(); ?></span><div><h4>Firmanız için ilk adımı atın</h4><p>Firma bilgilerinizi ve fotoğrafınızı ekleyin. Başvurunuzun durumunu buradan takip edin.</p><a href="<?php echo esc_url(home_url('/firma-ekle/')); ?>">İlk firmamı ekle <span aria-hidden="true">→</span></a></div></div><?php endif; ?></div>
<details class="mis360-measurement-note"><summary>İstatistik ayrıntıları</summary><p>Son 30 gün: <?php echo (int)$totals['phone']; ?> telefon, <?php echo (int)$totals['whatsapp']; ?> WhatsApp ve <?php echo (int)$totals['directions']; ?> yol tarifi tıklaması. Firmalarınıza gelen yayınlanmış yorum: <?php echo (int)$review_count; ?>.</p><p>Ölçüm başlangıcı: <?php echo esc_html(get_option('mis360_metrics_since','Henüz başlamadı')); ?>. Önceki ziyaretler dahil değildir. Aynı ziyaretçinin 30 dakika içindeki tekrarları sayılmaz. Tıklamalar, tamamlanan görüşme veya satış sayısı değildir.</p></details>
<?php endif; if($account_section==='firmalar'): ?>
<section id="account-firms" class="mis360-account-panel"><header><div><h2>Firmalarım</h2><p><?php echo (int)$live; ?> yayında · <?php echo (int)$pending; ?> onay bekliyor</p></div><span><?php echo count($owned); ?> kayıt</span></header>
<?php if($firms->posts): foreach($firms->posts as $firm): $m=$metrics[$firm->ID]??array(); ?>
<?php $account_image=get_the_post_thumbnail_url($firm->ID,'thumbnail') ?: get_post_meta($firm->ID,'_firma_image_url',true); ?>
<article class="mis360-account-firm">
<div class="mis360-account-firm-image"><?php if($account_image): ?><img src="<?php echo esc_url($account_image); ?>" alt="" width="64" height="64" loading="lazy"><?php else: ?><span aria-hidden="true"><?php echo esc_html(mb_substr($firm->post_title,0,1)); ?></span><?php endif; ?></div>
<div class="mis360-account-firm-body"><h3><?php echo esc_html($firm->post_title); ?></h3><p><?php echo esc_html(implode(' / ',array_filter(array(get_post_meta($firm->ID,'_firma_city',true),get_post_meta($firm->ID,'_firma_district',true))))); ?> <span>· <?php echo (int)($m['view']??0); ?> görüntülenme</span></p>
<div class="mis360-account-firm-meta"><span class="mis360-account-status status-<?php echo esc_attr($firm->post_status); ?>"><?php echo esc_html(mis360_firm_review_label($firm->ID)); ?></span><span class="mis360-plan-tag"><?php echo esc_html(mis360_requested_plan_label($firm->ID)?:'Paket belirtilmemiş'); ?></span></div>
<?php if(get_post_meta($firm->ID,'_mis360_review_state',true)==='changes' && get_post_status($firm->ID)==='draft'): ?><p class="mis360-review-notice"><strong>Yönetici açıklaması:</strong> <?php echo nl2br(esc_html(get_post_meta($firm->ID,'_mis360_review_note',true))); ?></p><?php endif; ?>
<div class="mis360-account-contact-counts"><?php echo (int)($m['phone']??0); ?> telefon · <?php echo (int)($m['whatsapp']??0); ?> WhatsApp · <?php echo (int)($m['directions']??0); ?> yol tarifi</div></div>
<div class="mis360-account-row-actions"><?php mis360_firm_controls($firm->ID); ?><?php if($firm->post_status==='publish'): ?><a href="<?php echo esc_url(get_permalink($firm)); ?>">İlanı gör ↗</a><?php endif; ?><a href="<?php echo esc_url(mis360_account_url('odemeler')); ?>">Paket / ödeme</a></div>
</article>
<?php endforeach; ?><nav aria-label="Firma sayfaları"><?php echo paginate_links(array('base'=>add_query_arg('mpage','%#%',mis360_account_url('firmalar')),'format'=>'','current'=>$page,'total'=>$firms->max_num_pages)); ?></nav><?php else: ?><div class="mis360-account-empty">Henüz bir firma başvurunuz yok. İlk firmanızı ekleyerek başlayın.</div><?php endif; ?></section>
<?php endif; if($account_section==='yorumlar'): ?><section id="account-reviews" class="mis360-account-panel"><header><div><h2>Müşteri yorumları</h2><p>Sitede yayınlanan son 10 yorum · Toplam <?php echo $review_count; ?></p></div></header><?php if($reviews):foreach($reviews as $review): ?><article class="mis360-account-review"><strong><?php echo esc_html($review->comment_author); ?></strong><small><?php echo esc_html(get_the_title($review->comment_post_ID)); ?> · <?php echo esc_html(get_comment_date('d.m.Y',$review)); ?></small><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags($review->comment_content),45)); ?></p></article><?php endforeach;else: ?><div class="mis360-account-empty">Firmalarınıza henüz yayınlanmış yorum gelmedi.</div><?php endif; ?><p class="mis360-account-footnote">Dış kaynaklardan alınmış firma puanları bu yorum sayısına dahil değildir.</p></section>
<?php endif; if($account_section==='odemeler'): ?><section id="account-payments" class="mis360-account-panel"><header><div><h2>Ödeme durumu</h2><p>Yönetici tarafından kaydedilen son durum</p></div></header><p class="mis360-account-footnote">Online ödeme henüz aktif değil. Paket tercihi, ödeme yapıldığı veya ücretli paketin açıldığı anlamına gelmez.</p><?php if($firms->posts):foreach($firms->posts as $firm): ?><div class="mis360-account-payment"><strong><?php echo esc_html($firm->post_title); ?></strong><span><?php echo esc_html(mis360_firm_payment($firm->ID)); ?></span><?php $updated=get_post_meta($firm->ID,'_firma_payment_updated',true);if($updated): ?><small>Güncelleme: <?php echo esc_html($updated); ?></small><?php endif; ?></div><?php endforeach;else: ?><div class="mis360-account-empty">Görüntülenecek ödeme kaydı yok.</div><?php endif; ?><?php if($firms->max_num_pages>1): ?><nav aria-label="Ödeme sayfaları"><?php echo paginate_links(array('base'=>add_query_arg('mpage','%#%',mis360_account_url('odemeler')),'format'=>'','current'=>$page,'total'=>$firms->max_num_pages)); ?></nav><?php endif; ?></section><?php endif; ?>

<?php if($account_section==='destek'):
 if(current_user_can('manage_options')): ?>
 <section class="mis360-account-panel"><h2>Yönetici destek merkezi</h2><p>Üyelerin mesajlarını WordPress yönetim panelinden yanıtlayabilirsiniz.</p><a class="mis360-member-button" href="<?php echo esc_url(admin_url('admin.php?page=mis360-support')); ?>">Canlı Destek ekranını aç →</a></section>
 <?php else: mis360_support_ui(); endif; endif; ?>

<?php if($account_section==='bildirimler')mis360_notifications_panel();if($account_section==='sahiplenme')mis360_claim_panel(); ?>
